version: '3'

services:
  ros-master:
    image: noetic_desktop
    network_mode: "host"
    command: stdbuf -o L roscore
    restart: always

  localization:
    image: noetic_desktop
    container_name: localization
    privileged: True
    depends_on:
      - ros-master
    network_mode: "host"
    environment:
      - "DISPLAY=$DISPLAY"
      - "XAUTHORITY=/tmp/.docker.xauth"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    command: ["/bin/bash", "-c", "cd catkin_ws; source devel/setup.bash; roslaunch robot_project localization.launch --wait;"]

  spawn:
    image: noetic_desktop
    container_name: spawn
    privileged: True
    depends_on:
      - ros-master
    network_mode: "host"
    environment:
      - "DISPLAY=$DISPLAY"
      - "XAUTHORITY=/tmp/.docker.xauth"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    command: ["/bin/bash", "-c", "cd catkin_ws; source devel/setup.bash; roslaunch robot_project spawn.launch --wait"]
