version: '3'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: noetic_desktop
    networks:
      - ros
    command: stdbuf -o L roscore
    restart: always

  spawn:
    image: noetic_desktop
    container_name: spawn
    privileged: True
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY=$DISPLAY"
      - "XAUTHORITY=/tmp/.docker.xauth"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    command: ["/bin/bash", "-c", "cd catkin_ws; source devel/setup.bash; roslaunch robot_project spawn.launch --wait"]

  path_planning:
    image: noetic_desktop
    container_name: path_planning
    privileged: True
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY=$DISPLAY"
      - "XAUTHORITY=/tmp/.docker.xauth"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    command: ["/bin/bash", "-c", "cd catkin_ws; source devel/setup.bash; roslaunch robot_project path_planning.launch --wait;"]

  send_goals:
    image: noetic_desktop
    container_name: send_goals
    privileged: True
    depends_on:
      - ros-master
    networks:
      - ros
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "DISPLAY=$DISPLAY"
      - "XAUTHORITY=/tmp/.docker.xauth"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    command: [ "/bin/bash", "-c", "cd catkin_ws; source devel/setup.bash; rosrun robot_project navigation_goals;" ]