footprint: [[-0.5, -0.4], [-0.5, 0.4], [0.6, 0.5], [0.6, -0.5]]
footprint_padding: 0.1

robot_base_frame: link_chassis
update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 3.0
raytrace_range: 3.5
cost_scaling_factor: 3.0

# layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /laser/scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
